version: "3.9"
services:
    service:
        build:
            context: ./
            dockerfile: dockerfile
        container_name: service_face_anti_spoofing
        ports:
            - 5002:5002
        restart: unless-stopped
        deploy:
          resources:
            reservations:
              devices:
              - driver: nvidia
                count: 1
                device_ids: ['0']
                capabilities: [gpu]
